### ISSUE TITLE
Upgrade docset

### ISSUE THREAD

**Issue by j-min** [iamaziz/PyTorch-docset#3]
Thank you for sharing this docset!
Do you have plan to maintain this docset?
If not, could you please explain how you created `.tgz` file with pytorch documentation? Thanks in advance.

**Comment by iamaziz** [comment]
Hi @j-min thanks for the ping! I just pushed a [PR](https://github.com/Kapeli/Dash-User-Contributions/pull/1512) for updating to version 0.2.0.

The `.tgz` file is the compressed version of the final `.docset`. The main documentation of Dash's docsets has some description on how to create it (see the `tar` command [here](https://github.com/Kapeli/Dash-User-Contributions#contribute-a-new-docset)), it's already in the script, see [L131](https://github.com/iamaziz/PyTorch-docset/blob/master/pytorch2docset.py#L131).

There is, however, a room for improving the docset (see #1) feel free to PR :)

**Comment by iamaziz** [comment]
Just pushed another [PR](https://github.com/Kapeli/Dash-User-Contributions/pull/1513) to add TOC.

**Comment by j-min** [comment]
Thank you!
